name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Loại build'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android ${{ github.event.inputs.build_type || 'debug' }}
          buildozer_version: master
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: xsmb-apk
          path: ${{ steps.buildozer.outputs.filename }}
